apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-dns
  namespace: kube-system
data:
  stubDomains: |
    {"yb-demo-asia-northeast2-a.svc.cluster.local": ["10.174.0.4"], "yb-demo-asia-northeast1-a.svc.cluster.local": ["10.146.0.3"], "yb-demo-australia-southeast1-b.svc.cluster.local": ["10.152.0.3"]}
